-- Base de datos para utilizar con el ejemplo de capas

CREATE DATABASE BD_EJEMPLO_LINQ
GO

USE BD_EJEMPLO_LINQ
GO

-- CREACIÓN DE TABLAS ______________________________________________________

CREATE TABLE CLIENTES(
	ID_CLIENTE int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOMBRE varchar(80) NOT NULL,
	TELEFONO varchar(11) NULL,
	DIRECCION varchar(80) NULL,
)

CREATE TABLE RESERVACIONES(
	NUMRESERVACION INT IDENTITY PRIMARY KEY,
	ID_CLIENTE INT NOT NULL FOREIGN KEY REFERENCES CLIENTES(ID_CLIENTE),
	FECHAINGRESO DATETIME NOT NULL,
	FECHASALIDA DATETIME NOT NULL,
	CANTIDADPERSONAS INT CHECK (CANTIDADPERSONAS>0) NOT NULL,
	TIPOHABITACION VARCHAR(10) CHECK(TIPOHABITACION IN('STANDARD','JUNIOR','DELUXE')) NOT NULL,
	PRECIO_NOCHE INT NOT NULL,
	CANCELADA BIT DEFAULT 0
)
GO

-- CREACIÓN DE VISTAS ____________________________________________________

CREATE VIEW CONSULTA_RESERVA AS
SELECT  NUMRESERVACION, T2.ID_CLIENTE,NOMBRE,TELEFONO,
		FECHAINGRESO,FECHASALIDA,DATEDIFF(DD,FECHAINGRESO,FECHASALIDA) AS NOCHES,
		CANTIDADPERSONAS,TIPOHABITACION,PRECIO_NOCHE,
		PRECIO_NOCHE*DATEDIFF(DD,FECHAINGRESO,FECHASALIDA)*CANTIDADPERSONAS AS SUBTOTAL,
		(PRECIO_NOCHE*DATEDIFF(DD,FECHAINGRESO,FECHASALIDA)*CANTIDADPERSONAS)*0.05 AS ICT,
		(PRECIO_NOCHE*DATEDIFF(DD,FECHAINGRESO,FECHASALIDA)*CANTIDADPERSONAS)*0.13 AS IVA,
		CANCELADA
FROM	RESERVACIONES T1 INNER JOIN CLIENTES T2
ON		T1.ID_CLIENTE=T2.ID_CLIENTE
GO

-- CREACIÓN DE PROCEDIMIENTOS ALMACENADOS _________________________________

CREATE PROCEDURE ELIMINAR
		@idcliente int,  --recibe un id
		@msj varchar(50) out   --devuelve un mensaje
AS BEGIN
if (not exists(select * from CLIENTES where ID_CLIENTE=@idcliente))
	begin
		set @msj='El cliente no existe'
		return 0
	end
else
	begin
		DELETE from CLIENTES where ID_CLIENTE=@idcliente
		set @msj='Cliente eliminado'
		return 1
	end
END
GO

-- INSERTAR DATOS EN LAS TABLAS 

INSERT INTO CLIENTES(NOMBRE, TELEFONO, DIRECCION)
VALUES	('Alejandra Alfaro Arias', '88-88-88-01', 'San José'), 
		('Brenda Brenes Bonilla', '88-88-88-02', 'Heredia'), 
		('Carlos Contreras Castro', '88-88-88-03', 'Cartago'), 
		('Daniel Días Durán', '88-88-88-04', 'Alajuela'), 
		('Elias Esquivel Esquivel', '88-88-88-05', 'Puntarenas'), 
		('Francisco Flores Flores', '88-88-88-06', 'Guanacaste'), 
		('Gabriela Gómez González', '88-88-88-07', 'Limón'), 
		('Héctor Herrera Hidalgo', '88-88-88-08', 'Alajuela'), 
		('Ileana Ibarra Ibarra', '88-88-88-09', 'Guanacaste'), 
		('Juan Juárez Jiménez', '88-88-88-10', 'Puntarenas'), 
		('Karla Keller Kooper', '88-88-88-11', 'Cartago'), 
		('Laura Loría Loría', '88-88-88-12', 'San José'), 
		('Mónica Méndez Madriz', '88-88-88-13', 'Guanacaste'); 

INSERT INTO RESERVACIONES(ID_CLIENTE, FECHAINGRESO, FECHASALIDA, CANTIDADPERSONAS, TIPOHABITACION, PRECIO_NOCHE)
VALUES	(1, '20220702', '20220705', 2, 'DELUXE', 300000),
		(1, '20231215', '20231219', 4, 'DELUXE', 320000),
		(2, '20220704', '20220708', 3, 'STANDARD', 180000),
		(2, '20221201', '20221203', 5, 'JUNIOR', 175000),
		(2, '20231118', '20231121', 3, 'DELUXE', 320000),
		(3, '20230816', '20230819', 6, 'STANDARD', 180000);


-- CREACIÓN DE CONSULTAS 

SELECT * FROM CLIENTES;

SELECT * FROM RESERVACIONES;
