#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoWeb
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_EJEMPLO_LINQ")]
	public partial class BD_HOTELDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCLIENTES(CLIENTES instance);
    partial void UpdateCLIENTES(CLIENTES instance);
    partial void DeleteCLIENTES(CLIENTES instance);
    partial void InsertRESERVACIONES(RESERVACIONES instance);
    partial void UpdateRESERVACIONES(RESERVACIONES instance);
    partial void DeleteRESERVACIONES(RESERVACIONES instance);
    #endregion
		
		public BD_HOTELDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BD_EJEMPLO_LINQConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BD_HOTELDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BD_HOTELDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BD_HOTELDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BD_HOTELDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CLIENTES> CLIENTES
		{
			get
			{
				return this.GetTable<CLIENTES>();
			}
		}
		
		public System.Data.Linq.Table<RESERVACIONES> RESERVACIONES
		{
			get
			{
				return this.GetTable<RESERVACIONES>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ELIMINAR")]
		public int ELIMINAR([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idcliente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string msj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idcliente, msj);
			msj = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLIENTES")]
	public partial class CLIENTES : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CLIENTE;
		
		private string _NOMBRE;
		
		private string _TELEFONO;
		
		private string _DIRECCION;
		
		private EntitySet<RESERVACIONES> _RESERVACIONES;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CLIENTEChanging(int value);
    partial void OnID_CLIENTEChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnTELEFONOChanging(string value);
    partial void OnTELEFONOChanged();
    partial void OnDIRECCIONChanging(string value);
    partial void OnDIRECCIONChanged();
    #endregion
		
		public CLIENTES()
		{
			this._RESERVACIONES = new EntitySet<RESERVACIONES>(new Action<RESERVACIONES>(this.attach_RESERVACIONES), new Action<RESERVACIONES>(this.detach_RESERVACIONES));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CLIENTE", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CLIENTE
		{
			get
			{
				return this._ID_CLIENTE;
			}
			set
			{
				if ((this._ID_CLIENTE != value))
				{
					this.OnID_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._ID_CLIENTE = value;
					this.SendPropertyChanged("ID_CLIENTE");
					this.OnID_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="VarChar(11)")]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this.OnTELEFONOChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO = value;
					this.SendPropertyChanged("TELEFONO");
					this.OnTELEFONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="VarChar(80)")]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this.OnDIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._DIRECCION = value;
					this.SendPropertyChanged("DIRECCION");
					this.OnDIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTES_RESERVACIONES", Storage="_RESERVACIONES", ThisKey="ID_CLIENTE", OtherKey="ID_CLIENTE")]
		public EntitySet<RESERVACIONES> RESERVACIONES
		{
			get
			{
				return this._RESERVACIONES;
			}
			set
			{
				this._RESERVACIONES.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RESERVACIONES(RESERVACIONES entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTES = this;
		}
		
		private void detach_RESERVACIONES(RESERVACIONES entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTES = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RESERVACIONES")]
	public partial class RESERVACIONES : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NUMRESERVACION;
		
		private int _ID_CLIENTE;
		
		private System.DateTime _FECHAINGRESO;
		
		private System.DateTime _FECHASALIDA;
		
		private int _CANTIDADPERSONAS;
		
		private string _TIPOHABITACION;
		
		private int _PRECIO_NOCHE;
		
		private System.Nullable<bool> _CANCELADA;
		
		private EntityRef<CLIENTES> _CLIENTES;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNUMRESERVACIONChanging(int value);
    partial void OnNUMRESERVACIONChanged();
    partial void OnID_CLIENTEChanging(int value);
    partial void OnID_CLIENTEChanged();
    partial void OnFECHAINGRESOChanging(System.DateTime value);
    partial void OnFECHAINGRESOChanged();
    partial void OnFECHASALIDAChanging(System.DateTime value);
    partial void OnFECHASALIDAChanged();
    partial void OnCANTIDADPERSONASChanging(int value);
    partial void OnCANTIDADPERSONASChanged();
    partial void OnTIPOHABITACIONChanging(string value);
    partial void OnTIPOHABITACIONChanged();
    partial void OnPRECIO_NOCHEChanging(int value);
    partial void OnPRECIO_NOCHEChanged();
    partial void OnCANCELADAChanging(System.Nullable<bool> value);
    partial void OnCANCELADAChanged();
    #endregion
		
		public RESERVACIONES()
		{
			this._CLIENTES = default(EntityRef<CLIENTES>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMRESERVACION", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NUMRESERVACION
		{
			get
			{
				return this._NUMRESERVACION;
			}
			set
			{
				if ((this._NUMRESERVACION != value))
				{
					this.OnNUMRESERVACIONChanging(value);
					this.SendPropertyChanging();
					this._NUMRESERVACION = value;
					this.SendPropertyChanged("NUMRESERVACION");
					this.OnNUMRESERVACIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CLIENTE", DbType="Int NOT NULL")]
		public int ID_CLIENTE
		{
			get
			{
				return this._ID_CLIENTE;
			}
			set
			{
				if ((this._ID_CLIENTE != value))
				{
					if (this._CLIENTES.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._ID_CLIENTE = value;
					this.SendPropertyChanged("ID_CLIENTE");
					this.OnID_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHAINGRESO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHAINGRESO
		{
			get
			{
				return this._FECHAINGRESO;
			}
			set
			{
				if ((this._FECHAINGRESO != value))
				{
					this.OnFECHAINGRESOChanging(value);
					this.SendPropertyChanging();
					this._FECHAINGRESO = value;
					this.SendPropertyChanged("FECHAINGRESO");
					this.OnFECHAINGRESOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHASALIDA", DbType="DateTime NOT NULL")]
		public System.DateTime FECHASALIDA
		{
			get
			{
				return this._FECHASALIDA;
			}
			set
			{
				if ((this._FECHASALIDA != value))
				{
					this.OnFECHASALIDAChanging(value);
					this.SendPropertyChanging();
					this._FECHASALIDA = value;
					this.SendPropertyChanged("FECHASALIDA");
					this.OnFECHASALIDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANTIDADPERSONAS", DbType="Int NOT NULL")]
		public int CANTIDADPERSONAS
		{
			get
			{
				return this._CANTIDADPERSONAS;
			}
			set
			{
				if ((this._CANTIDADPERSONAS != value))
				{
					this.OnCANTIDADPERSONASChanging(value);
					this.SendPropertyChanging();
					this._CANTIDADPERSONAS = value;
					this.SendPropertyChanged("CANTIDADPERSONAS");
					this.OnCANTIDADPERSONASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPOHABITACION", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TIPOHABITACION
		{
			get
			{
				return this._TIPOHABITACION;
			}
			set
			{
				if ((this._TIPOHABITACION != value))
				{
					this.OnTIPOHABITACIONChanging(value);
					this.SendPropertyChanging();
					this._TIPOHABITACION = value;
					this.SendPropertyChanged("TIPOHABITACION");
					this.OnTIPOHABITACIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO_NOCHE", DbType="Int NOT NULL")]
		public int PRECIO_NOCHE
		{
			get
			{
				return this._PRECIO_NOCHE;
			}
			set
			{
				if ((this._PRECIO_NOCHE != value))
				{
					this.OnPRECIO_NOCHEChanging(value);
					this.SendPropertyChanging();
					this._PRECIO_NOCHE = value;
					this.SendPropertyChanged("PRECIO_NOCHE");
					this.OnPRECIO_NOCHEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANCELADA", DbType="Bit")]
		public System.Nullable<bool> CANCELADA
		{
			get
			{
				return this._CANCELADA;
			}
			set
			{
				if ((this._CANCELADA != value))
				{
					this.OnCANCELADAChanging(value);
					this.SendPropertyChanging();
					this._CANCELADA = value;
					this.SendPropertyChanged("CANCELADA");
					this.OnCANCELADAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTES_RESERVACIONES", Storage="_CLIENTES", ThisKey="ID_CLIENTE", OtherKey="ID_CLIENTE", IsForeignKey=true)]
		public CLIENTES CLIENTES
		{
			get
			{
				return this._CLIENTES.Entity;
			}
			set
			{
				CLIENTES previousValue = this._CLIENTES.Entity;
				if (((previousValue != value) 
							|| (this._CLIENTES.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CLIENTES.Entity = null;
						previousValue.RESERVACIONES.Remove(this);
					}
					this._CLIENTES.Entity = value;
					if ((value != null))
					{
						value.RESERVACIONES.Add(this);
						this._ID_CLIENTE = value.ID_CLIENTE;
					}
					else
					{
						this._ID_CLIENTE = default(int);
					}
					this.SendPropertyChanged("CLIENTES");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
